version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    networks: 
        - api-network

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks: 
        - api-network

volumes:
  postgres_data:

networks:
  api-network:
    driver: bridge