version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - $DATABASE_PORT:$DATABASE_PORT
    networks: 
        - api-network

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks: 
        - api-network

volumes:
  postgres_data:

networks:
  api-network:
    driver: bridge